Completed homework 2
m-tetiana/aqa-advanced-1 pull request #2
Opened 2023-09-02 10:04 UTC by m-tetiana

2023-09-02 11:18 UTC, sttaran requested changes

2023-09-02 11:18 UTC, sttaran commented on js_basics/task5.1.js
> +const area = Math.PI * radius  * radius
use `Math.pow(radius, 2)` or `radius ** 2`. It will make your code more readable

2023-09-02 11:18 UTC, sttaran commented on js_basics/task5.3.js
> +const volume = Math.PI * radius * radius * height
use `Math.pow(radius, 2)` or `radius ** 2`. It will make your code more readable

2023-09-03 11:02 UTC, m-tetiana commented on js_basics/task5.1.js
> +const area = Math.PI * radius  * radius
Fixed

2023-09-03 11:02 UTC, m-tetiana commented on js_basics/task5.3.js
> +const volume = Math.PI * radius * radius * height
Fixed

2023-09-05 17:15 UTC, merged